version: "3"
services:
  mongo:
    container_name: mongodb
    hostname: mongodb
    image: mongo:5.0.6
    environment:
      - MONGO_REPLICA_SET_NAME=rs0
    volumes:
      - mongodb:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - default
    command: "--bind_ip_all --replSet rs0 --port 27017"
volumes:
  mongodb:
networks:
  default:
